### ISSUE TITLE
Plugin is not updating  temperature and humidity any more

### ISSUE THREAD

**Issue by ortoberi** [alesf/homebridge-arso#2]
Hi,

for Ljubljana (LJUBL-ANA_BEZIGRAD, I didn't check for others) temperature and humidity is not loading/updating any more.

In the morning response in the log file was:
[20/04/2021, 06:30:39] [ARSO] weather: successful response | {"rain":0,"snow":0,"temperature":4.8,"humidity":94}

but for some time is:
[20/04/2021, 14:26:05] [ARSO] weather: successful response | {"rain":0,"snow":0}

Maybe ARSO changed something in the XML file.

BR,
David

**Comment by alesf** [comment]
They're apparently having problems with gathering data from that station at the moment.
Most of the values in their XML are empty.

http://www.meteo.si/uploads/probase/www/observ/surface/text/sl/observationAms_LJUBL-ANA_BEZIGRAD_latest.xml

**Comment by ortoberi** [comment]
Thx for the quick response!

I also see in the logs that Meteo server was down: [20/04/2021, 13:06:03] [ARSO] weather: bad response (http://www.meteo.si/uploads/probase/www/observ/surface/text/sl/observationAms_LJUBL-ANA_BEZIGRAD_latest.xml): ESOCKETTIMEDOUT

I hope they will solve the problem.

Thx again,
David

**Comment by alesf** [comment]
You're welcome.
Their services are pretty reliable though.
